version: '3.4'

services:
  kartaca_ws:
    build:
      context: .
      dockerfile: ./Dockerfile
  pythonapp:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pythonapp.rule=Host(`kartaca.localhost`) && Path(`/pythonapp`)"
      - "traefik.http.services.pythonapp.loadbalancer.server.port=4444"
    restart: always
    build:
      context: ./pythonapp
      dockerfile: ./Dockerfile
    ports:
      - "4444:4444"
    depends_on:
      - mongo
  goapp:
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goapp.rule=Host(`kartaca.localhost`) && Path(`/goapp`)"
      - "traefik.http.services.goapp.loadbalancer.server.port=5555"
    build:
      context: ./goapp  
      dockerfile: ./Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - mongo
  servis_gelistirme:
    build: 
      context: ./servis_gelistirme
      dockerfile: ./Dockerfile
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.address=:8081"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=harunkurt0000@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--providers.file.filename=/etc/traefik/rules.yml"
    ports:
      - "80:80"
      - "8081:8081"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
      - "./traefik/rules.yml:/etc/traefik/rules.yml"
      - "./traefik/dashboard:/traefik"
networks:
  kartaca:
    driver: bridge