version: '3.4'

services:
  kartaca_ws:
    build:
      context: .
      dockerfile: ./Dockerfile
  pythonapp:
    restart: always
    build:
      context: ./flask_app
      dockerfile: ./Dockerfile
  servis_gelistirme:
    build: 
      context: ./servis_gelistirme
      dockerfile: ./Dockerfile
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin


http:
  routers:
    pythonapp:
      rule: "Host(`kartaca.localhost`) && PathPrefix(`/pythonapp`)"
      service: "pythonapp"
    goapp:
      rule: "Host(`kartaca.localhost`) && PathPrefix(`/goapp`)"
      service: "goapp"
    grafana:
      rule: "Host(`kartaca.localhost`) && PathPrefix(`/grafana`)"
      service: "grafana"
  services:
    pythonapp:
      loadBalancer:
        servers:
          - url: "http://pythonapp:5000/staj"
    goapp:
      loadBalancer:
        servers:
          - url: "http://goapp:8080/staj"
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
