# global:
#   scrape_interval:     15s
#   evaluation_interval: 15s

# scrape_configs:
#   - job_name: "node-exporter"
#     static_configs:
#       - targets: ["node-exporter:9100"]
#   - job_name: "cadvisor"
#     static_configs:
#       - targets: ["cadvisor:8080"]


global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

remote_write:
  - url: "http://prometheus-pushgateway:9091/write"

remote_read:
  - url: "http://prometheus-pushgateway:9091/read"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

