http:
  routers:
    pythonapp:
      entryPoints:
        - web
      rule: "Host(`kartaca.localhost`) && PathPrefix(`/pythonapp`)"
      # rule: "PathPrefix(`/pythonapp`)"
      service: pythonapp
    goapp:
      entryPoints:
        - web
      rule: "Host(`kartaca.localhost`) && PathPrefix(`/goapp`)"
      # rule: "PathPrefix(`/goapp`)"
      service: goapp
    # grafana:
    #   rule: "Host(`kartaca.localhost`) && PathPrefix(`/grafana`)"
    #   service: grafana
  services:
    pythonapp:
      loadBalancer:
        servers:
          - url: "http://pythonapp:4444"
    goapp:
      loadBalancer:
        servers:
          - url: "http://goapp:5555"
    # grafana:
    #   image: grafana/grafana
    #   container_name: grafana
    #   volumes:
    #     - "./grafana/data:/var/lib/grafana"
    #   environment:
    #     - GF_SECURITY_ADMIN_PASSWORD=<your-grafana-password>
